### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by ghost** [utaresearch/gPET#1]
Hi,
I have problems with the compilation. I am using CUDA 10.2 with Ubuntu 18.04.1 with gcc(7.5.0)

When I do:
nvcc *.o kernal/*.o -o gPET.x 
I get the following error:
/usr/bin/ld: kernal/gPET_kernals.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC

I am able to compile it as static with:
nvcc *.o kernal/*.o -o gPET.x  -Xlinker "-static"

But then I get a segmentation fault during the execution (when the iniDevice function is called to initialize the GPU).
I don´t know if there is a compilation option that may be used, or if the gPET_kernals.o file can be compiled with other options.
Thanks

**Comment by laiyf94** [comment]
From what you wrote here, the issue maybe due to the * in the compilation.
Please try nvcc *.o ./kernal/*.o -o gPET

**Comment by laiyf94** [comment]
From what you wrote here, you can try compile the code with
nvcc *.o ./kernal/*.o -o gPET -Xcompile -fPIC.
Notice the star in the compilation.
This issue is not repeated in our machine. If it continues, we will consider posting a docker version.

**Comment by ghost** [comment]
Thanks for the answer. 
I have tried this, but I still got the same error.
It seems that the problem is the precompiled gPET_kernals.o file
Could you please compile that file (gPET_kernals.o) with the -Xcompiler -fPIC option and post it?
BTW, I also tried to compile it with CUDA 10.0 (as it is indicated version in the README file), but in that case, the error is:
nvlink fatal   : Input file 'kernal/gPET_kernals.o' newer than toolkit (102 vs 100)
So I guess, that the gPET_kernals.o object file was compiled with CUDA 10.2.
Thanks

**Comment by YujieChi** [comment]
Hi there,
The source code of gPET.cu has been uploaded. Please refer to the updated readme for proper usage. 
Thanks.

**Comment by ghost** [comment]
Thanks,
Now, I've been able to compile it without any problem.
