### ISSUE TITLE
Output information

### ISSUE THREAD

**Issue by ghost** [utaresearch/gPET#2]
Hi,
Is there any document with the description of the output format? The input is well described but I cannot find similar documentation on how to read the generated binary output files.
Of course, this can be extracted from the gPET.cu code, looking at the lines where the output is written, but maybe there is already a document with that info. 
Thanks,

**Comment by laiyf94** [comment]
Thank you for the comment. A MATLAB code about reading output is uploaded. And the readMe file is updated accordingly.
