### ISSUE TITLE
Missing /output 

### ISSUE THREAD

**Issue by ghost** [utaresearch/gPET#3]
Hi, 
The /output folder is missing from the repository. It needs to be created before running the code. Otherwise, the gPET gives an error without further information. 
I think that placing the readOutput.m file in that /output folder could be useful, as it would be already available there to analyze the generated output data. 
Thanks again.

**Comment by YujieChi** [comment]
Hi @x-cov ,

Thanks for the suggestion.  The issue has been fixed in #4
